stages:
  - analysis

sonarqube:
  stage: analysis
  tags:
    - vue-admin
  image: ahgora/gitlab-sonar-scanner
  variables:
    SONAR_URL: https://sonar-dev.clp.kr
    SONAR_ANALYSIS_MODE: publish
  script:
    - gitlab-sonar-scanner
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
