// export * from "@/pages/login";
export * from "@/pages/home";
// export * as Campus from "@/pages/campus";
export * from "@/pages/signup";
export * as Employee from "@/pages/employee";
export * as Organization from "@/pages/organization";
export * from "@/pages/testLogin";
export * from "@/pages/group";
export * from "@/pages/getStarted";
export * from "@/pages/companySearch";
export * from "@/pages/companySearchResult";
export * from "@/pages/informationInput";
